# Generated by Django 5.2.2 on 2025-06-08 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='descripcion',
            new_name='description',
        ),
    ]
